### ISSUE TITLE
No swagger json generated

### ISSUE THREAD

**Issue by belgoros** [drewish/rspec-rails-swagger#42]
I tried to generate `swagger.json` file by running `bundle exec rake swagger`but nothing was generated.

I created an [example app](https://github.com/belgoros/draft-api/tree/rspec-rails-swagger) to reproduce it.

What am I missing ? Thank you.

**Comment by drewish** [comment]
Do you get any output from the rake task?

**Comment by belgoros** [comment]
@drewish I figured out why nothing happened, - I had `rspec-rails-swagger` gem declared in `test` group only (my bad). After moving it to `development, test` fixed the problem and the rake task has generated `swagger.json` file. I pushed the modifications to the [corresponding branch](https://github.com/belgoros/draft-api/tree/rspec-rails-swagger). Thank you.

It would be great to put a link on how to embed Swagger UI as well.

**Comment by drewish** [comment]
Oh awesome, glad you got it figured out. I'd started to pull down your repo but was waiting on the new ruby version to install.

I've been using Redoc and find it to be a much nicer experience. I haven't had a chance to find a nice way of embedding that though.
