### ISSUE TITLE
swagger_doc tag doesn't work

### ISSUE THREAD

**Issue by zddhub** [drewish/rspec-rails-swagger#43]
As [comments](https://github.com/drewish/rspec-rails-swagger/blob/5e6127c08f2a4e362204a525267e02b5ad5ebad2/spec/swagger_helper.rb#L16) or [rswag](https://github.com/domaindrivendev/rswag#global-metadata) (rspec-rails-swagger based on rswag):

>   By default, the operations defined in spec files are added to the first document below. You can override this behavior by adding a `swagger_doc` tag to the the root example_group in your specs, e.g.

```ruby
describe '...', swagger_doc: 'v2/swagger.json'
```

But it doesn't work if I used it with RSpec, like below:
```ruby
RSpec.describe 'mock allocation summary', type: :request, swagger_doc: 'v2/swagger.yml' do
...
    path '/post' do
...
end
```

Is there anybody have some idea?

**Comment by zddhub** [comment]
Got some idea from source code https://github.com/drewish/rspec-rails-swagger/blob/5e6127c08f2a4e362204a525267e02b5ad5ebad2/lib/rspec/rails/swagger/request_builder.rb#L20

I found a workaround way:

```ruby
RSpec.describe 'mock allocation summary', type: :request, swagger_doc: 'v2/swagger.yml' do
...
    path '/post', swagger_document: 'v2/swagger.yml' do
...
end
```

It works but not perfect ???

**Comment by drewish** [comment]
Ah yeah I would have though it would work the way you expected. Looking at the helper:

https://github.com/drewish/rspec-rails-swagger/blob/f8fb9d45db317c948bc7b3f7a9152731e0e74271/lib/rspec/rails/swagger/helpers.rb#L48

It seems like it should looking for a document in the following order: 
- `attributes` hash passed in to the `path` call
- `metadata` passed down from the parent context block
- default to the first of the documents

So I'll look at adding a PR to fix this.

**Comment by drewish** [comment]
Give https://github.com/drewish/rspec-rails-swagger/pull/45 a look and see how that works for you.
