### ISSUE TITLE
What design choices make it different from rswag (swagger_rails)?

### ISSUE THREAD

**Issue by knarewski** [drewish/rspec-rails-swagger#53]
I was researching the options for automated documentation of my Rails project, and encountered this gem. It mentions being heavily influenced by `swagger_rails`, but does not say why it was created in the first place and what are the benefits of choosing it over `swagger_rails`. The DSL and capabilities look quite similar. Is it worth adding a sentence or two about that in the readme to help people choose?

**Comment by drewish** [comment]
The interface is very similar but at that point swagger_rails' code structure was very hard to work with and the maintainer and I differed on how to address it so I decided to create my own gem. I'm not actively using any more so the other gem might be a better option at this point.
